### ISSUE TITLE
[Feature]: Investigate linters being used across different dev stages

### ISSUE THREAD

**Issue by chrisreddington** [github/gh-skyline#15]
### Description

The `devcontainer` is configured for Go development. The GitHub Action build action uses `super-linter`. It's worth checking that the same linters are configured across all areas for consistency, and reducing friction/churn in the process.

### Requirements

- Ensure all stages are using the same linters.
- These list of linters should be clearly documented (including how to update/manage them for each phase/stage).

### Definition of Done

- [x] The same linters are being used across all stages.
- [x] Relevant documentation is updated
- [x] Unit tests are updated/written and passing

**Comment by jeffbrownpaloalto-dev** [comment]
1<>.
