### ISSUE TITLE
[Feature]: Skip STL generation and the `GitHub Skyline` ascii art text

### ISSUE THREAD

**Issue by mattr-** [github/gh-skyline#36]
### Description

I'd like the ability to generate only the ascii art portion of the skyline without the `GitHub Skyline` ASCII art and without generating an STL file. Why? I'd like to include the skyline as part of an overall dashboard I'm working on for my terminal setup.

### Requirements

Provide CLI flag (`--only-art`?) that does the following:
- Removes the ASCII art for `GitHub Skyline`
- Prevents the generation of an STL file on disk.

I'd like to run something like `gh skyline --art-only --year 2023` and have
```
                                                ╻
 ╻               ╻      ╻ ╻╻                   ╻░
 ░  ╻╻  ╻   ╽┃  ╻░╻ ╻   ░ ░░ ╻    ╻    ╻╻╻╻ ╻ ╻░░
╻░┃╻▒░╻╻░  ╻░░╻╻░░░╻░╻ ╻░ ░░╻░╻  ╻░ ╻╻╻░░░░ ░ ░░░
░░░░░░░░░  ░░▓░░░░░░░░ ░░ ░░░░░  ░░╻░░░░░░░╻░╻░░░╻╻
░░░░░▒░░░ ╻░░▒░░░░░░░░╻░░ ░░░░░╻ ░░░░░░░░░░░░░░░░░░╻
░░░░░▒░░░░░▒░▒░▓░▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
```

be the only output. (This is my real skyline from the year 2023 😄)

### Definition of Done

- [ ] The request is fulfilled
- [ ] Relevant documentation is updated
- [ ] Unit tests are updated/written and passing

**Comment by chrisreddington** [comment]
Thanks for the feature request @mattr- 😄 This is an interesting request, as Skyline has typically centered around the 3D printing of the STL models. I added the ASCII art as a new addition for this CLI format, so I'm glad to see that you're enjoying that ❤️ (It brings me joy when I see it appear!)

Overall, I'm seeing a few GitHub Issues with a similar theme of 'customisability' (e.g. being able to customise the STL a bit more, or only have ASCII art, and no STL generated). This is an interesting request, and I think could be explored further.

For now, I'll unassigned this issue, so consider it triaged 🎉 😄 If anyone might be interested in taking a look, please do let me know!

**Comment by ephyran** [comment]
Hi! I'm interested in working on this issue. As requested, just letting you know I'll be taking a look at this and working on a PR!

**Comment by chrisreddington** [comment]
Thank you to @ephyran for working on this, and to @mattr- for the suggestion. This has been merged and will be part of the next release 🎉
