### ISSUE TITLE
[Feature]: Renaming the file to "2020-24" for consistency with the naming inside the file

### ISSUE THREAD

**Issue by Laotree** [github/gh-skyline#42]
### Description

Regarding the years, the naming inside the file uses "2020-24," but the file name is "20-24." Would you consider changing the file name to "2020-24" to maintain consistency

### Requirements

- Ensure consistency in the year format

### Definition of Done

- [x] Refactor the logic of the year format
- [x] Relevant documentation is updated
- [x] Unit tests are updated/written and passing

**Comment by chrisreddington** [comment]
Thanks for raising this @Laotree! This is fixed via #56 😄

**Comment by Laotree** [comment]
> Thanks for raising this @Laotree! This is fixed via #56 😄

[ASCII Art](https://private-user-images.githubusercontent.com/791642/393260436-8ddda088-ac5a-4020-8ae0-ef0d4825f6a1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MzA0NTksIm5iZiI6MTczNTUzMDE1OSwicGF0aCI6Ii83OTE2NDIvMzkzMjYwNDM2LThkZGRhMDg4LWFjNWEtNDAyMC04YWUwLWVmMGQ0ODI1ZjZhMS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQwMzQyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmNjMTlmNmYyNzRiYWExN2QwZjI0MmQ1MjcwMTVjMTU4NDA5ZmVhMmViZTllOGQyZThkMWY1MmY5MmE3Y2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ChGYqLNuIwD1e6dJIrTiHC6O0LpjDakoEAC_zUhQRe4) in README.md should be updated as listed in tasks `Relevant documentation is updated`
