### ISSUE TITLE
[Bug]: ASCII art for empty contribution shows grid filled with all high-level blocks

### ISSUE THREAD

**Issue by siddharthkoli** [github/gh-skyline#50]
### GitHub CLI Version

2.63.2

### gh-skyline Version

0.0.4

### What Operating System are you seeing the problem on?

Linux

### What happened?

Running the extension for an empty contribution graph gives a grid filled with all high-level blocks.
I ran it with `-u chrisreddington` and `-y 2013`.

![image](https://github.com/user-attachments/assets/55acf7f1-57a2-4873-86f4-7ab4978f9c6d)

Running with `-f` however outputs blank blocks.
![image](https://github.com/user-attachments/assets/553f2465-1cf1-47d9-99c1-c14dd2a6602a)

Is that the expected behaviour or a bug?

PS: I ran it on Codespaces

**Comment by chrisreddington** [comment]
An interesting bug, thanks @siddharthkoli 🙏. I think the code normalises based on all contributions that have come back, so if you pick an empty year, then 'everything' would appear the same.

Replicated on my side, so I'll remove the triage label. Could be a good issue if anyone is up for taking a look at this one!

**Comment by siddharthkoli** [comment]
Can I work on this?

**Comment by siddharthkoli** [comment]
> I assume the expected behaviour would be to see a grid of gaps, rather than a grid of blocks? So I think an approach to a fix could be checking whether there were any contributions throughout that period.

The same as -f flag in the screenshot? A grid of gaps is essentially empty right?

**Comment by chrisreddington** [comment]
> Can I work on this please? I was looking for good first issues for contributing. 🙂

That would be great, thank you 🎉 🙏 



> > I assume the expected behaviour would be to see a grid of gaps, rather than a grid of blocks? So I think an approach to a fix could be checking whether there were any contributions throughout that period.
> 
> The same as -f flag in the screenshot? A grid of gaps is essentially empty right?

Yep, exactly that 😄 I think the difference with `-f` or `--full` is that it pulls in data from other years, which means a 'zero' contribution is an empty contribution. Whereas if you happen to pick a year that has no contributions, then they all get normalised to being a contribution.

**Comment by siddharthkoli** [comment]
@chrisreddington 

<img width="769" alt="image" src="https://github.com/user-attachments/assets/7d222071-0dcd-46b3-b7e9-f9883219ffd0" />

is this fine or would it be better if I collapsed the blank space completely like with the `-f` option I posted in the initial comment?
